const LIST_GENERATED_BY_CHAT_GPT: string[] = [
    "2QcClBMJ4X0p69h5ISXP45",
    "4DBHvtrLpwv5ZrhObEtGwA",
    "3rHdCZ0XpHFQYCluyHlm0w",
    "14KtkIpsvzDSCXR24EqHCL",
    "5RVeM2nZy52ve01J7k1FOe",
    "633sCJZB3RfunwiQjzIpvX",
    "5pMia1lBFZyj4VVa0wzrNV",
    "44imBReuLDHuIP0j4UmCtm",
    "6sPkDFYJLQ1eNNjURZbAoZ",
    "1kqBP6eE24L0agNpnTIKtc",
];

const VOICES_WORTH_LISTENING_TO: string[] = [
    "5qSUyCrk9KR69lEiXbjwXM",
    "2hmkzUtix0qTqvtpPcMzEL",
    "41zWZdWCpVQrKj7ykQnXRc",
    "6E709HRH7XaiZrMfgtNCun",
    "4rOoJ6Egrf8K2IrywzwOMk",
    "7gozmLqbcbr6PScMjc0Zl4",
    "2cmAMcaKRH65JBCJ4U01XP",
];

const MOSAIC_OF_EPISODES: string[] = [
    "0nQvE0UReQ8jAce78qbArY",
    "48LKI7lC83P1n6cno5Lllp",
    "7xg3dgRvXDNROIbohgUzsV",
    "2cRxXSWIFOK3fteKxeiPAO",
    "7GvmlF69IiIcBSZXyyCyCH",
    "3Xfe2CjnagyIOX6qoYWvGC",
    "12dWyq0MRgomLrvBHQFjdZ",
];

const LEGENDS_OF_ROCK: string[] = [
    "0ETFjACtuP2ADo6LFhL6HN",
    "2UJcKiJxNryhL050F5Z1Fk",
    "1bt6q2SruMsBtcerNVtpZB",
    "3PRoXYsngSwjEQWR5PsHWR",
    "5U4dnRZsfW8NmwBBkELFPh",
    "6FCzvataOZh68j8OKzOt9a",
];

const ICONS_OF_MUSIC: string[] = [
    "2ANVost0y2y52ema1E9xAZ",
    "6mUdeDZCsExyJLMdAfDuwh",
    "4LH4d3cOWNNsVw41Gqt2kv",
    "6QaVfG1pHYl1z15ZxkvVDW",
    "7JVJlkNNobS0GSoy4tCS96",
    "2Lgsa7jbu86SK5zJVFCh3S",
    "5duyQokC4FMcWPYTV9Gpf9",
]

export const STANDARD_FEEDS = [
        {
            name: "List Generated By Chat GPT",
            type: "playlist",
            ids: LIST_GENERATED_BY_CHAT_GPT,
        },
        {
            name: "Legends of Rock",
            type: "album",
            ids: LEGENDS_OF_ROCK,
        },
        {
            name: "Icons of Music",
            type: "album",
            ids: ICONS_OF_MUSIC,
        },
        {
            name: "Voices Worth Listening To",
            type: "show",
            ids: VOICES_WORTH_LISTENING_TO,
        },
        {
            name: "Mosaic Of Episodes",
            type: "episode",
            ids: MOSAIC_OF_EPISODES,
        },
        
]